# Generated by Django 4.2.5 on 2024-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='error_prob',
            field=models.FloatField(default=0),
        ),
    ]
