# Generated by Django 4.2.5 on 2024-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_process_algo'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='alpha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='beta',
            field=models.FloatField(default=1),
        ),
    ]
